package com.threeseeds.app.theme

import androidx.compose.ui.graphics.Color

/**
 * The full board-theme catalog: 24 appearances, 10 of them free so a
 * fresh profile can rotate immediately, the rest purchasable with
 * coins earned from play (see [com.threeseeds.app.profile.Economy]).
 *
 * Prices cluster at 0 / 75 / 150 / 250 so the shop reads as tiers
 * rather than a wall of one-off numbers.
 */
object ThemeCatalog {

    const val DEFAULT_ID = "indigo-night"

    val ALL: List<GameTheme> = listOf(
        // ---- Free (10) ----
        GameTheme(
            id = "indigo-night",
            name = "Indigo Night",
            cost = 0,
            backgroundStops = listOf(Color(0xFF0D1026), Color(0xFF241B4D), Color(0xFF101338)),
            lineColor = Color(0xFF7C87FF),
            lineGlowColor = Color(0x667C87FF),
            nodeColor = Color(0xFFA9B0FF),
            playerOne = Color(0xFFFFB020),
            playerOneDeep = Color(0xFFF57C00),
            playerTwo = Color(0xFF3ED8F0),
            playerTwoDeep = Color(0xFF00A5C4),
            surfaceColor = Color(0xFF191D42),
            accentColor = Color(0xFFFF4081),
            motif = Motif.NONE,
            motifColor = Color(0xFFFFFFFF),
        ),
        GameTheme(
            id = "blossom",
            name = "Blossom",
            cost = 0,
            backgroundStops = listOf(Color(0xFF2B1030), Color(0xFF4A1B46), Color(0xFF1E0F2B)),
            lineColor = Color(0xFFFFB6C8),
            lineGlowColor = Color(0x66FFB6C8),
            nodeColor = Color(0xFFFFD7E3),
            playerOne = Color(0xFFFFE08A),
            playerOneDeep = Color(0xFFFFB74D),
            playerTwo = Color(0xFFFF8FB3),
            playerTwoDeep = Color(0xFFD81B60),
            surfaceColor = Color(0xFF3A1640),
            accentColor = Color(0xFFFF80AB),
            motif = Motif.PETALS,
            motifColor = Color(0xFFFFC1D6),
        ),
        GameTheme(
            id = "dragon-fire",
            name = "Dragon Fire",
            cost = 0,
            backgroundStops = listOf(Color(0xFF1A0B06), Color(0xFF3D1206), Color(0xFF0F0704)),
            lineColor = Color(0xFFFF8A50),
            lineGlowColor = Color(0x66FF8A50),
            nodeColor = Color(0xFFFFB74D),
            playerOne = Color(0xFFFFD54F),
            playerOneDeep = Color(0xFFFFA000),
            playerTwo = Color(0xFFFF5252),
            playerTwoDeep = Color(0xFFD32F2F),
            surfaceColor = Color(0xFF2B1209),
            accentColor = Color(0xFFFF6E40),
            motif = Motif.DRAGON,
            motifColor = Color(0xFFFFAB40),
        ),
        GameTheme(
            id = "ocean",
            name = "Ocean",
            cost = 0,
            backgroundStops = listOf(Color(0xFF04121F), Color(0xFF0A2E4A), Color(0xFF031019)),
            lineColor = Color(0xFF64FFDA),
            lineGlowColor = Color(0x6664FFDA),
            nodeColor = Color(0xFF80D8FF),
            playerOne = Color(0xFFFFF176),
            playerOneDeep = Color(0xFFFFD54F),
            playerTwo = Color(0xFF40C4FF),
            playerTwoDeep = Color(0xFF0288D1),
            surfaceColor = Color(0xFF0C2233),
            accentColor = Color(0xFF18FFFF),
            motif = Motif.BUBBLES,
            motifColor = Color(0xFF80D8FF),
        ),
        GameTheme(
            id = "cosmic",
            name = "Cosmic",
            cost = 0,
            backgroundStops = listOf(Color(0xFF0B0620), Color(0xFF1A0B3D), Color(0xFF050414)),
            lineColor = Color(0xFFB388FF),
            lineGlowColor = Color(0x66B388FF),
            nodeColor = Color(0xFFD1C4E9),
            playerOne = Color(0xFFFFF59D),
            playerOneDeep = Color(0xFFFFCA28),
            playerTwo = Color(0xFF7C4DFF),
            playerTwoDeep = Color(0xFF512DA8),
            surfaceColor = Color(0xFF150C33),
            accentColor = Color(0xFFEA80FC),
            motif = Motif.STARS,
            motifColor = Color(0xFFE6E1FF),
        ),
        GameTheme(
            id = "emerald",
            name = "Emerald",
            cost = 0,
            backgroundStops = listOf(Color(0xFF04150F), Color(0xFF0A2E1E), Color(0xFF020F0A)),
            lineColor = Color(0xFF69F0AE),
            lineGlowColor = Color(0x6669F0AE),
            nodeColor = Color(0xFFB9F6CA),
            playerOne = Color(0xFFFFF59D),
            playerOneDeep = Color(0xFFF9A825),
            playerTwo = Color(0xFF64DD17),
            playerTwoDeep = Color(0xFF33691E),
            surfaceColor = Color(0xFF0D2B1E),
            accentColor = Color(0xFF00E676),
            motif = Motif.LEAVES,
            motifColor = Color(0xFF69F0AE),
        ),
        GameTheme(
            id = "neon",
            name = "Neon",
            cost = 0,
            backgroundStops = listOf(Color(0xFF120024), Color(0xFF31005F), Color(0xFF09001A)),
            lineColor = Color(0xFF18FFFF),
            lineGlowColor = Color(0x6618FFFF),
            nodeColor = Color(0xFFFF4081),
            playerOne = Color(0xFFFFEA00),
            playerOneDeep = Color(0xFFFF6D00),
            playerTwo = Color(0xFF00E5FF),
            playerTwoDeep = Color(0xFF0091EA),
            surfaceColor = Color(0xFF1D0040),
            accentColor = Color(0xFFEA80FC),
            motif = Motif.SPARKLES,
            motifColor = Color(0xFFEA80FC),
        ),
        GameTheme(
            id = "marble",
            name = "Marble",
            cost = 0,
            backgroundStops = listOf(Color(0xFFEDEFF5), Color(0xFFD9DDE8), Color(0xFFF7F8FC)),
            lineColor = Color(0xFF5C6BC0),
            lineGlowColor = Color(0x555C6BC0),
            nodeColor = Color(0xFF7986CB),
            playerOne = Color(0xFFFF8F00),
            playerOneDeep = Color(0xFFE65100),
            playerTwo = Color(0xFF29B6F6),
            playerTwoDeep = Color(0xFF01579B),
            surfaceColor = Color(0xFFFFFFFF),
            accentColor = Color(0xFF5C6BC0),
            motif = Motif.GEOMETRIC,
            motifColor = Color(0xFF9FA8DA),
        ),
        GameTheme(
            id = "sunset",
            name = "Sunset",
            cost = 0,
            backgroundStops = listOf(Color(0xFF25103A), Color(0xFF6D2A52), Color(0xFF160B26)),
            lineColor = Color(0xFFFFAB91),
            lineGlowColor = Color(0x66FFAB91),
            nodeColor = Color(0xFFFFCCBC),
            playerOne = Color(0xFFFFD180),
            playerOneDeep = Color(0xFFFF9100),
            playerTwo = Color(0xFFE57373),
            playerTwoDeep = Color(0xFFC62828),
            surfaceColor = Color(0xFF35164A),
            accentColor = Color(0xFFFF8A65),
            motif = Motif.BOKEH,
            motifColor = Color(0xFFFFAB91),
        ),
        GameTheme(
            id = "arctic",
            name = "Arctic",
            cost = 0,
            backgroundStops = listOf(Color(0xFF0A1A2F), Color(0xFF16324F), Color(0xFF060F1D)),
            lineColor = Color(0xFF81D4FA),
            lineGlowColor = Color(0x6681D4FA),
            nodeColor = Color(0xFFB3E5FC),
            playerOne = Color(0xFFFFF8E1),
            playerOneDeep = Color(0xFFFFECB3),
            playerTwo = Color(0xFF4FC3F7),
            playerTwoDeep = Color(0xFF0277BD),
            surfaceColor = Color(0xFF12263F),
            accentColor = Color(0xFF40C4FF),
            motif = Motif.SNOW,
            motifColor = Color(0xFFE1F5FE),
        ),

        // ---- 75 coins (5) ----
        GameTheme(
            id = "candy",
            name = "Candy Pop",
            cost = 75,
            backgroundStops = listOf(Color(0xFF2A0A2E), Color(0xFF5A1657), Color(0xFF17031A)),
            lineColor = Color(0xFFFF80AB),
            lineGlowColor = Color(0x66FF80AB),
            nodeColor = Color(0xFFFFC1E3),
            playerOne = Color(0xFFFFD748),
            playerOneDeep = Color(0xFFFFB300),
            playerTwo = Color(0xFFEA80FC),
            playerTwoDeep = Color(0xFFAB47BC),
            surfaceColor = Color(0xFF3B1140),
            accentColor = Color(0xFFFF4081),
            motif = Motif.CONFETTI,
            motifColor = Color(0xFFFFC1E3),
        ),
        GameTheme(
            id = "volcanic",
            name = "Volcanic",
            cost = 75,
            backgroundStops = listOf(Color(0xFF160605), Color(0xFF3A0A06), Color(0xFF0C0303)),
            lineColor = Color(0xFFFF7043),
            lineGlowColor = Color(0x66FF7043),
            nodeColor = Color(0xFFFFAB91),
            playerOne = Color(0xFFFFC107),
            playerOneDeep = Color(0xFFFF6F00),
            playerTwo = Color(0xFFFF3D00),
            playerTwoDeep = Color(0xFFBF360C),
            surfaceColor = Color(0xFF23100C),
            accentColor = Color(0xFFFF5722),
            motif = Motif.EMBERS,
            motifColor = Color(0xFFFF6E40),
        ),
        GameTheme(
            id = "bamboo",
            name = "Bamboo Grove",
            cost = 75,
            backgroundStops = listOf(Color(0xFF0D1A0A), Color(0xFF1F3D14), Color(0xFF070F06)),
            lineColor = Color(0xFFC5E1A5),
            lineGlowColor = Color(0x66C5E1A5),
            nodeColor = Color(0xFFDCEDC8),
            playerOne = Color(0xFFFFE082),
            playerOneDeep = Color(0xFFF9A825),
            playerTwo = Color(0xFFAED581),
            playerTwoDeep = Color(0xFF558B2F),
            surfaceColor = Color(0xFF14290F),
            accentColor = Color(0xFFFFD54F),
            motif = Motif.LEAVES,
            motifColor = Color(0xFFC5E1A5),
        ),
        GameTheme(
            id = "desert",
            name = "Desert Dunes",
            cost = 75,
            backgroundStops = listOf(Color(0xFF2B1B0E), Color(0xFF5D3A1A), Color(0xFF150D06)),
            lineColor = Color(0xFFFFCC80),
            lineGlowColor = Color(0x66FFCC80),
            nodeColor = Color(0xFFFFE0B2),
            playerOne = Color(0xFFFFD54F),
            playerOneDeep = Color(0xFFF57F17),
            playerTwo = Color(0xFFBDBDBD),
            playerTwoDeep = Color(0xFF616161),
            surfaceColor = Color(0xFF33210F),
            accentColor = Color(0xFFFFB74D),
            motif = Motif.SPARKLES,
            motifColor = Color(0xFFFFE0B2),
        ),
        GameTheme(
            id = "galaxy-pixel",
            name = "Galaxy Pixel",
            cost = 75,
            backgroundStops = listOf(Color(0xFF050510), Color(0xFF101038), Color(0xFF02020A)),
            lineColor = Color(0xFF76FF03),
            lineGlowColor = Color(0x6676FF03),
            nodeColor = Color(0xFFB9F6CA),
            playerOne = Color(0xFFFFEA00),
            playerOneDeep = Color(0xFFFF6F00),
            playerTwo = Color(0xFF18FFFF),
            playerTwoDeep = Color(0xFF0091EA),
            surfaceColor = Color(0xFF0D0D2B),
            accentColor = Color(0xFF76FF03),
            motif = Motif.GEOMETRIC,
            motifColor = Color(0xFF76FF03),
        ),

        // ---- 150 coins (5) ----
        GameTheme(
            id = "rose",
            name = "Rose Garden",
            cost = 150,
            backgroundStops = listOf(Color(0xFF1F0A18), Color(0xFF4A1230), Color(0xFF12060F)),
            lineColor = Color(0xFFFF6F91),
            lineGlowColor = Color(0x66FF6F91),
            nodeColor = Color(0xFFFFB1C1),
            playerOne = Color(0xFFFFF176),
            playerOneDeep = Color(0xFFFFB300),
            playerTwo = Color(0xFFE57373),
            playerTwoDeep = Color(0xFFAD1457),
            surfaceColor = Color(0xFF2E1122),
            accentColor = Color(0xFFFF4081),
            motif = Motif.FLOWERS,
            motifColor = Color(0xFFFF80AB),
        ),
        GameTheme(
            id = "sakura-night",
            name = "Sakura Night",
            cost = 150,
            backgroundStops = listOf(Color(0xFF150A20), Color(0xFF3E1435), Color(0xFF0B0614)),
            lineColor = Color(0xFFFFC1D6),
            lineGlowColor = Color(0x66FFC1D6),
            nodeColor = Color(0xFFFFE4EC),
            playerOne = Color(0xFFFFF176),
            playerOneDeep = Color(0xFFFFCA28),
            playerTwo = Color(0xFFF8BBD0),
            playerTwoDeep = Color(0xFFEC407A),
            surfaceColor = Color(0xFF241030),
            accentColor = Color(0xFFFF80AB),
            motif = Motif.PETALS,
            motifColor = Color(0xFFFFC1D6),
        ),
        GameTheme(
            id = "moonlit",
            name = "Moonlit Fireflies",
            cost = 150,
            backgroundStops = listOf(Color(0xFF070B1E), Color(0xFF131B3D), Color(0xFF04060F)),
            lineColor = Color(0xFFC5CAE9),
            lineGlowColor = Color(0x66C5CAE9),
            nodeColor = Color(0xFFE8EAF6),
            playerOne = Color(0xFFFFF9C4),
            playerOneDeep = Color(0xFFFBC02D),
            playerTwo = Color(0xFF9FA8DA),
            playerTwoDeep = Color(0xFF3949AB),
            surfaceColor = Color(0xFF101736),
            accentColor = Color(0xFFFFF176),
            motif = Motif.FIREFLIES,
            motifColor = Color(0xFFE6FF8A),
        ),
        GameTheme(
            id = "frost",
            name = "Frostbite",
            cost = 150,
            backgroundStops = listOf(Color(0xFF0B1F24), Color(0xFF173940), Color(0xFF050F13)),
            lineColor = Color(0xFF80DEEA),
            lineGlowColor = Color(0x6680DEEA),
            nodeColor = Color(0xFFB2EBF2),
            playerOne = Color(0xFFFFFFFF),
            playerOneDeep = Color(0xFFCFD8DC),
            playerTwo = Color(0xFF4DD0E1),
            playerTwoDeep = Color(0xFF00838F),
            surfaceColor = Color(0xFF10292F),
            accentColor = Color(0xFF18FFFF),
            motif = Motif.SNOW,
            motifColor = Color(0xFFE0F7FA),
        ),
        GameTheme(
            id = "dragon-scale",
            name = "Dragon Scale",
            cost = 150,
            backgroundStops = listOf(Color(0xFF041A16), Color(0xFF0C3630), Color(0xFF020E0C)),
            lineColor = Color(0xFF1DE9B6),
            lineGlowColor = Color(0x661DE9B6),
            nodeColor = Color(0xFF64FFDA),
            playerOne = Color(0xFFFFD748),
            playerOneDeep = Color(0xFFFF8F00),
            playerTwo = Color(0xFF69F0AE),
            playerTwoDeep = Color(0xFF00BFA5),
            surfaceColor = Color(0xFF0A2723),
            accentColor = Color(0xFF1DE9B6),
            motif = Motif.SCALES,
            motifColor = Color(0xFF64FFDA),
        ),
        GameTheme(
            id = "fountain-court",
            name = "Fountain Court",
            cost = 150,
            backgroundStops = listOf(Color(0xFF061426), Color(0xFF0E3350), Color(0xFF04101D)),
            lineColor = Color(0xFF80DEEA),
            lineGlowColor = Color(0x6680DEEA),
            nodeColor = Color(0xFFB2EBF2),
            playerOne = Color(0xFFFFF176),
            playerOneDeep = Color(0xFFFFCA28),
            playerTwo = Color(0xFF4FC3F7),
            playerTwoDeep = Color(0xFF0288D1),
            surfaceColor = Color(0xFF0B2438),
            accentColor = Color(0xFF18FFFF),
            motif = Motif.FOUNTAIN,
            motifColor = Color(0xFF80DEEA),
        ),

        // ---- 250 coins (4) ----
        GameTheme(
            id = "tropical",
            name = "Tropical Lagoon",
            cost = 250,
            backgroundStops = listOf(Color(0xFF06231C), Color(0xFF0B5541), Color(0xFF03110D)),
            lineColor = Color(0xFF00E5FF),
            lineGlowColor = Color(0x6600E5FF),
            nodeColor = Color(0xFF76FF03),
            playerOne = Color(0xFFFFEA00),
            playerOneDeep = Color(0xFFFF6F00),
            playerTwo = Color(0xFF00E676),
            playerTwoDeep = Color(0xFF00C853),
            surfaceColor = Color(0xFF0A352A),
            accentColor = Color(0xFFFFEA00),
            motif = Motif.FLOWERS,
            motifColor = Color(0xFFFFAB40),
        ),
        GameTheme(
            id = "copper-gears",
            name = "Copper Gears",
            cost = 250,
            backgroundStops = listOf(Color(0xFF1A120B), Color(0xFF3E2A16), Color(0xFF0E0906)),
            lineColor = Color(0xFFFFB74D),
            lineGlowColor = Color(0x66FFB74D),
            nodeColor = Color(0xFFFFCC80),
            playerOne = Color(0xFFFFCC80),
            playerOneDeep = Color(0xFFE08200),
            playerTwo = Color(0xFF80CBC4),
            playerTwoDeep = Color(0xFF00695C),
            surfaceColor = Color(0xFF26190E),
            accentColor = Color(0xFFFFAB40),
            motif = Motif.GEOMETRIC,
            motifColor = Color(0xFFFFB74D),
        ),
        GameTheme(
            id = "aurora",
            name = "Aurora Borealis",
            cost = 250,
            backgroundStops = listOf(Color(0xFF041229), Color(0xFF0A3D3A), Color(0xFF030A18)),
            lineColor = Color(0xFF69F0AE),
            lineGlowColor = Color(0x667C4DFF),
            nodeColor = Color(0xFFB388FF),
            playerOne = Color(0xFF69F0AE),
            playerOneDeep = Color(0xFF00C853),
            playerTwo = Color(0xFFB388FF),
            playerTwoDeep = Color(0xFF7C4DFF),
            surfaceColor = Color(0xFF072033),
            accentColor = Color(0xFF69F0AE),
            motif = Motif.BOKEH,
            motifColor = Color(0xFF69F0AE),
        ),
        GameTheme(
            id = "heritage-wood",
            name = "Heritage Wood",
            cost = 250,
            backgroundStops = listOf(Color(0xFF1C110A), Color(0xFF3A2416), Color(0xFF100A06)),
            lineColor = Color(0xFFD7CCC8),
            lineGlowColor = Color(0x66D7CCC8),
            nodeColor = Color(0xFFBCAAA4),
            playerOne = Color(0xFFFFCC80),
            playerOneDeep = Color(0xFFE65100),
            playerTwo = Color(0xFFEFEBE9),
            playerTwoDeep = Color(0xFFA1887F),
            surfaceColor = Color(0xFF2A1A0F),
            accentColor = Color(0xFFFFB74D),
            motif = Motif.BOKEH,
            motifColor = Color(0xFFD7CCC8),
        ),
        GameTheme(
            id = "dragon-realm",
            name = "Dragon Realm",
            cost = 250,
            backgroundStops = listOf(Color(0xFF120304), Color(0xFF3A0A10), Color(0xFF0A0203)),
            lineColor = Color(0xFFFF7043),
            lineGlowColor = Color(0x66FF7043),
            nodeColor = Color(0xFFFFAB91),
            playerOne = Color(0xFFFFD54F),
            playerOneDeep = Color(0xFFFF8F00),
            playerTwo = Color(0xFFFF5252),
            playerTwoDeep = Color(0xFFC62828),
            surfaceColor = Color(0xFF240A0C),
            accentColor = Color(0xFFFF6E40),
            motif = Motif.DRAGON,
            motifColor = Color(0xFFFFB74D),
        ),
    )

    val DEFAULT: GameTheme = ALL.first { it.id == DEFAULT_ID }

    fun byId(id: String): GameTheme = ALL.firstOrNull { it.id == id } ?: DEFAULT

    /** The next unlocked theme after [currentId], wrapping around — the rotation order. */
    fun nextUnlocked(currentId: String, unlocked: Set<String>): GameTheme {
        val cycle = ALL.filter { it.id in unlocked }.ifEmpty { listOf(DEFAULT) }
        val currentIndex = cycle.indexOfFirst { it.id == currentId }
        return cycle[(currentIndex + 1).coerceAtLeast(0) % cycle.size]
    }
}
